---
title: ""
output:
  word_document:
    reference_docx: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(dplyr)
library(flextable)
library(officer)
```

```{r create-table}
# Data from the univariate ANOVA results
table_data <- tibble::tribble(
  ~metric_pretty, ~Df, ~statistic, ~p.value, ~sig,
  "Carbohydrate (mg cm⁻²)", 2, 10.047, 0.007, "**",
  "Tissue biomass (AFDW mg cm⁻²)", 2, 4.396, 0.111, "",
  "Protein (mg cm⁻²)", 2, 3.037, 0.219, "",
  "Growth", 2, 2.612, 0.271, "",
  "Zooxanthellae (cells cm⁻²)", 2, 1.697, 0.428, ""
)

# Create the flextable
table_s1 <- table_data %>%
  flextable() %>%
  set_header_labels(
    metric_pretty = "Response Variable",
    Df = "df",
    statistic = "F",
    p.value = "p",
    sig = ""
  ) %>%
  add_header_lines(values = c(
    "Table S1. Treatment effects on individual coral metrics",
    "Univariate linear mixed-effects models with reef as random intercept"
  )) %>%
  colformat_double(j = c("statistic", "p.value"), digits = 3) %>%
  bold(i = ~ sig != "", j = "sig") %>%
  align(align = "left", j = "metric_pretty", part = "body") %>%
  align(align = "center", j = c("Df", "statistic", "p.value", "sig"), part = "body") %>%
  align(align = "center", part = "header") %>%
  bold(part = "header", i = 1:2) %>%
  fontsize(size = 11, part = "all") %>%
  font(fontname = "Times New Roman", part = "all") %>%
  width(j = "metric_pretty", width = 3) %>%
  width(j = c("Df", "statistic", "p.value"), width = 0.8) %>%
  width(j = "sig", width = 0.5) %>%
  border_remove() %>%
  hline_top(border = fp_border(width = 2), part = "all") %>%
  hline(i = 1, border = fp_border(width = 1), part = "header") %>%
  hline(i = 2, border = fp_border(width = 2), part = "header") %>%
  hline_bottom(border = fp_border(width = 2), part = "body") %>%
  padding(padding = 3, part = "all")

table_s1
```

**Note:** Significance codes: \*\* p < 0.01, \* p < 0.05. Models tested the effect of treatment (1, 3, or 6 corals) on individual coral physiological metrics and growth. Only carbohydrate content showed a significant treatment effect.
